//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAnalyzers.MultithreadingAnalyzer.Test.AbandonLock {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartAnalyzers.MultithreadingAnalyzer.Test.AbandonLock.TestCases", typeof(TestCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Threading;
        ///
        ///namespace SmartAnalyzers.MultithreadingAnalyzer.Test.AbandonLock.TestData
        ///{
        ///    class _001_LockAcquiredOutsideTryClause
        ///    {
        ///        private readonly object myLockObj = new object();
        ///
        ///        public void DoSth1()
        ///        {
        ///            Monitor.Enter(myLockObj);
        ///            try
        ///            {
        ///
        ///            }
        ///            finally
        ///            {
        ///                Monitor.Exit(myLockObj);
        ///            }
        ///        }
        ///
        ///        public void DoSth2()
        ///        {
        ///            var lo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _001_LockAcquiredOutsideTryClause {
            get {
                return ResourceManager.GetString("_001_LockAcquiredOutsideTryClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Threading;
        ///
        ///namespace SmartAnalyzers.MultithreadingAnalyzer.Test.AbandonLock.TestData
        ///{
        ///    class _002_LockAcquiredInsideTryClause
        ///    {
        ///        private readonly object myLockObj = new object();
        ///
        ///        public void DoSth1()
        ///        {
        ///            try
        ///            {
        ///                Monitor.Enter(myLockObj);
        ///            }
        ///            finally
        ///            {
        ///                Monitor.Exit(myLockObj);
        ///            }
        ///        }
        ///
        ///        public void DoSth2()
        ///        {
        ///            var l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _002_LockAcquiredInsideTryClause {
            get {
                return ResourceManager.GetString("_002_LockAcquiredInsideTryClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Threading;
        ///
        ///namespace SmartAnalyzers.MultithreadingAnalyzer.Test.AbandonLock.TestData
        ///{
        ///    class _003_LockReleasedOutsideFinallyClause
        ///    {
        ///        private readonly object myLockObj = new object();
        ///
        ///        public void DoSth1()
        ///        {
        ///            Monitor.Enter(myLockObj);
        ///            try
        ///            {
        ///
        ///            }
        ///            finally
        ///            {
        ///                Monitor.Exit(myLockObj);
        ///            }
        ///        }
        ///
        ///        public void DoSth2()
        ///        {
        ///            va [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _003_LockReleasedOutsideFinallyClause {
            get {
                return ResourceManager.GetString("_003_LockReleasedOutsideFinallyClause", resourceCulture);
            }
        }
    }
}
