//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAnalyzers.MultithreadingAnalyzer.Test.CopiedSpinLock {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartAnalyzers.MultithreadingAnalyzer.Test.CopiedSpinLock.TestCases", typeof(TestCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Threading;
        ///
        ///namespace SmartAnalyzers.MultithreadingAnalyzer.Test.CopiedSpinLock.TestData
        ///{
        ///    class _001_SpinLockPassByValue
        ///    {
        ///        public _001_SpinLockPassByValue(SpinLock spinLock)
        ///        {
        ///            
        ///        }
        ///
        ///        public void SynchronizeWith(SpinLock spinLock)
        ///        {
        ///
        ///        }
        ///    }
        ///
        ///    class SampleSpinlockWrapper1
        ///    {
        ///        public SampleSpinlockWrapper1(ref SpinLock spinLock)
        ///        {
        ///            
        ///        }
        ///
        ///        public void SynchronizeWi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _001_SpinLockPassByValue {
            get {
                return ResourceManager.GetString("_001_SpinLockPassByValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Threading;
        ///
        ///namespace SmartAnalyzers.MultithreadingAnalyzer.Test.CopiedSpinLock.TestData
        ///{
        ///    class _002_ReadonlySpinLock
        ///    {
        ///        private readonly SpinLock InvalidSpinLock = new SpinLock();
        ///        private SpinLock ValidSpinLock = new SpinLock();
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _002_ReadonlySpinLock {
            get {
                return ResourceManager.GetString("_002_ReadonlySpinLock", resourceCulture);
            }
        }
    }
}
